Repository HearMate/hear-mate-app, pull requests merged in 2025-05, with the labels that each got.

#26 Refactor logging
  .gitignore
  lib/modules/echo_parse/blocs/echo_parse_bloc.dart
  lib/modules/echo_parse/repositories/echo_parse_api_repository.dart
  lib/modules/hearing_test/blocs/hearing_test/hearing_test_bloc.dart
  lib/modules/hearing_test/repositories/hearing_test_sounds_player_repository.dart
  scripts/sound_divider.py
  scripts/sound_generator.py
Labels: enhancement

#33 Add CSV Generation from Server Response and Dual File Saving Logic
  lib/modules/echo_parse/blocs/echo_parse_bloc.dart
  lib/modules/echo_parse/blocs/echo_parse_event.dart
  lib/modules/echo_parse/screens/echo_parse_upload_done_page/echo_parse_upload_done_page.dart
  pubspec.yaml
Labels: enhancement

#37 Language support for menu pages
  lib/l10n/app_de.arb
  lib/l10n/app_en.arb
  lib/l10n/app_pl.arb
  lib/l10n/app_uk.arb
Labels: enhancement

#38 Project files cleanup
  .DS_Store
  .gitignore
  assets/.DS_Store
  ios/.DS_Store
  ios/.gitignore
  ios/Podfile.lock
  lib/.DS_Store
  lib/modules/.DS_Store
  lib/modules/echo_parse/.DS_Store
  lib/modules/echo_parse/screens/.DS_Store
  macos/.gitignore
  macos/Podfile.lock
Labels: invalid, low priority

#46 Project warnings resolved and dependency cleaned-up
  lib/main.dart
  lib/modules/echo_parse/blocs/echo_parse_bloc.dart
  lib/modules/echo_parse/repositories/echo_parse_api_repository.dart
  lib/modules/echo_parse/screens/echo_parse_upload_page/echo_parse_upload_page.dart
  lib/modules/hearing_test/blocs/hearing_test/hearing_test_bloc.dart
  lib/modules/hearing_test/repositories/hearing_test_sounds_player_repository.dart
  lib/modules/hearing_test/screens/hearing_test_page/hearing_test_page.dart
  lib/modules/hearing_test/screens/hearing_test_result_page/audiogram_chart.dart
  lib/utils/logger.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  packages/hm_locale/lib/hm_locale.dart
  packages/hm_locale/lib/src/bloc/hm_locale_bloc.dart
  packages/hm_locale/pubspec.lock
  packages/hm_locale/pubspec.yaml
  packages/hm_theme/lib/hm_theme.dart
  packages/hm_theme/lib/src/bloc/hm_theme_bloc.dart
  packages/hm_theme/lib/src/bloc/hm_theme_state.dart
  packages/hm_theme/pubspec.lock
  packages/hm_theme/pubspec.yaml
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: invalid, low priority

#47 Theme correction and UI enhancement
  assets/lotties/download_success.json
  assets/lotties/saved.json
  lib/data/languages.dart
  lib/home_page.dart
  lib/l10n/app_en.arb
  lib/main.dart
  lib/modules/echo_parse/blocs/echo_parse_bloc.dart
  lib/modules/echo_parse/blocs/echo_parse_event.dart
  lib/modules/echo_parse/blocs/echo_parse_state.dart
  lib/modules/echo_parse/blocs/tab_navigation_cubit.dart
  lib/modules/echo_parse/screens/echo_parse_collection_page/echo_parse_collection_page.dart
  lib/modules/echo_parse/screens/echo_parse_conversion_results_page/echo_parse_conversion_results_page.dart
  lib/modules/echo_parse/screens/echo_parse_home_page/echo_parse_home_page.dart
  lib/modules/echo_parse/screens/echo_parse_home_page/widgets/saved_file_item.dart
  lib/modules/echo_parse/screens/echo_parse_home_page/widgets/saved_file_section.dart
  lib/modules/echo_parse/screens/echo_parse_home_page/widgets/saved_files_tab.dart
  lib/modules/echo_parse/screens/echo_parse_home_page/widgets/upload_section.dart
  lib/modules/echo_parse/screens/echo_parse_home_page/widgets/upload_tab.dart
  lib/modules/echo_parse/screens/echo_parse_upload_done_page/echo_parse_upload_done_page.dart
  lib/modules/echo_parse/screens/echo_parse_upload_page/echo_parse_upload_page.dart
  lib/modules/echo_parse/screens/echo_parse_welcome_page/echo_parse_welcome_page.dart
  lib/modules/hearing_test/repositories/hearing_test_sounds_player_repository.dart
  lib/screens/settings_page.dart
  lib/widgets/hm_app_bar.dart
  packages/hm_locale/devtools_options.yaml
  packages/hm_theme/devtools_options.yaml
  packages/hm_theme/lib/hm_theme.dart
Labels: enhancement, high priority
